# Assumes that:
# 1. the following env variables are set:
# - ZIP_FILE_PATH
# - EXTENSION_DIR
# 2. repository checked out
# Effects:
# - builds and tests an extension, fails on error
# - packed extension.zip saved to env.ZIP_FILE_PATH if inputs.doNotPackZip == 'false'

name: "Build, test and pack WebExtension"
description: "Builds, tests, and packs extension dir into zip file"

inputs:
  doNotPackZip:
    description: 'Set `true` to omit pack step'
    required: false

runs:
  using: "composite"
  steps:
    - name: Pack directory to zip
      if: inputs.doNotPackZip != 'true'
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: ${{ env.EXTENSION_DIR }}
        zipFilePath: ${{ env.ZIP_FILE_PATH }}
